create table if not exists public.remuneration_config (
  id bigint generated by default as identity primary key,
  valor_base numeric not null default 0,
  valor_hora numeric not null default 0,
  valor_bonus numeric not null default 0,
  valor_aux_transporte numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_remuneration_config_singleton
  on public.remuneration_config ((id));

insert into public.remuneration_config (valor_base, valor_hora, valor_bonus, valor_aux_transporte)
select 0, 0, 0, 0
where not exists (select 1 from public.remuneration_config);
