create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  work_date date not null,
  start_time text not null,
  lunch_start_time text not null,
  lunch_end_time text not null,
  end_time text not null,
  total_minutes integer not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create index if not exists idx_time_entries_work_date
  on public.time_entries(work_date);

alter table public.time_entries enable row level security;

-- Mantém sem policy pública por padrão.
-- Com backend usando SUPABASE_SERVICE_ROLE_KEY, o acesso continua funcionando.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  login text not null,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_users_login_unique
  on public.users(lower(login));

alter table public.users enable row level security;
