create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  work_date date not null,
  start_time text not null,
  lunch_start_time text not null,
  lunch_end_time text not null,
  end_time text not null,
  total_minutes integer not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create index if not exists idx_time_entries_work_date
  on public.time_entries(work_date);

alter table public.time_entries enable row level security;

-- Mantém sem policy pública por padrão.
-- Com backend usando SUPABASE_SERVICE_ROLE_KEY, o acesso continua funcionando.
